spring:
  application:
    name: shop-service-consumer
  dubbo:
    application:
      id: shop-service-consumer
      name: shop-service-consumer
    registry:
      address: zookeeper://192.168.0.102:2181;zookeeper://192.168.0.102:2182;zookeeper://192.168.0.102:2183
